### ISSUE TITLE
Feature: Adding parameter to create only major version tag

### ISSUE THREAD

**Issue by ruzickap** [haya14busa/action-update-semver#2]
Hello.

I'm using the `action-update-semver` to tag the releases and it works great.
When I create release with tag `v1.1.0` it "autocreates" `v1`, `v1.1`.

I would like to use this tool to create only one tag `v1` for the GitHub Actions.

Like it's described here https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations - you only need the `v1` when tagging `v1.1.0` GitHub Actions.

Would it be possible to introduce some new parameter (for example `major_version_tag_only`) to create only major version tags (`v1`)? Like:

```yaml
      - uses: haya14busa/action-update-semver@v1
        with:
          major_version_tag_only: true
          github_token: ${{ secrets.github_token }}
```

Thank you...
